# **머신러닝/딥러닝 - 평가자 체크 리스트**

### 1. 다음은 Calc 클래스다

In [1]:
class Calc:
  def __init__(self):
    self.value = 0
  def add(self, val):
    self.value += val

위 클래스를 상속하는 UpgradeCalc를 만들고 값을 뺄수 있는 minus 메서드를 추가해보자.

In [2]:
# 이곳에 UpgradeCalc 작성
class UpgradeCalc(Calc):
   def minus(self, val):
      self.value -= val

In [3]:
#  즉 다음과 같이 동작할 수 있는 클래스를 만들어야 한다
cal = UpgradeCalc()
cal.add(10)
cal.minus(7)

print(cal.value)      # 10에서 7일 뺀 3을 출력

3

### 2. filter와 lambda를 사용하여 리스트 [1,-2,3,-5,8,-3]에서 음수를 모두 제거해 보자

* 결과 : [1,3,8]

In [4]:
#  이곳에 작성
data = [1,-2,3,-5,8,-3]
result = list(filter(lambda x: x > 0, data))
print(result)

[1, 3, 8]

### 3. 총 10줄로 이루어진 sample.txt 파일이 있다. sample.txt 파일의 숫자 값을 모두 읽어 총합과 평균 값을 구한 후 평균 값을 result.txt 파일에 쓰는 프로그램을 작성하시오
```
예)임의의 sample.txt는 연습장 등으로 각자 생성할 것
sample.txt
10
20
30
40
50
60
70
80
90
100

결과)  
result.txt
55.0
```

In [5]:
# 이곳에 작성
sample = open("./sample.txt", "rt")

sum = 0
count = 0
while True:
   readStr = sample.readline()
   if not readStr:
      break
   sum += int(readStr)
   count += 1
sample.close()

result = open("./result.txt", "wt")
result.write(str(sum/count))
result.close()

### 4. 다음과 같이 동작하는 클래스 Calculator 를 작성하세요

In [6]:
# 이곳에 작성
class Calculator:
   def __init__(self, numbers) :
      self.numbers = numbers
   
   def sum(self):
      sum = 0
      for i in self.numbers:
         sum += i
      return sum
   
   def avg(self):
      return self.sum()/len(self.numbers)

In [7]:
# 결과

cal1 = Calculator([1,2,3,4,5])
print(cal1.sum())    # 합계
print(cal1.avg())    # 평균

cal2 = Calculator([6,7,8,9,10])
print(cal2.sum())    # 합계
print(cal2.avg())    # 평균

15
3.0
40
8.0

### 5. 문자열을 입력받아 같은 문자가 연속적으로 반복되는 경우에 그 반복 횟수를 표시해 문자열을 압축하여 표시하는 함수를 생성하시오

* 입력 예시 : aaabbcccccca
* 출력 예시 : a3b2c6a1

In [8]:
# 이곳에 작성
text = "aaabbcccccca"
def wordCount(text):
   result = ""
   word = text[0]
   count = 1
   for t in text[1:]:
      if word != t:
         result += "%s%d" % (word, count)
         word = t
         count = 1
         continue
      count += 1
   result += "%s%d" % (word, count)
   return result

print(wordCount(text))

a3b2c6a1

### 6. ['Life', 'is', 'too', 'short'] 리스트를 Life is too short 문자열로 만들어 출력해 보자.(띄어쓰기 포함)

In [9]:
text = ['Life', 'is', 'too', 'short']
text = " ".join(text)
print(text)

Life is too short

### 7. 리스트 li 에서 중복 숫자를 제거해 보자.

In [10]:
li = [1, 1, 1, 2, 2, 3, 3, 3, 4, 4, 5]
# 이곳에 코드 작성

# 결과 : [1,2,3,4,5]
li = list(set(li))
print(li)

[1, 2, 3, 4, 5]

### 8. 아래와 같은 클래스 BankAccount을 생성하세요:

* 클래스 속성: account_number, balance
* 생성자: __init__(self, account_number, balance=0): account_number와 초기 잔액 balance(기본값 0)을 인자로 받아 객체를 초기화합니다.
* 메소드: deposit(self, amount): 계좌에 amount만큼 입금합니다.
* 메소드: withdraw(self, amount): 계좌에서 amount만큼 출금합니다. 잔액이 출금액보다 작을 경우 "잔액이 부족합니다"라고 출력합니다.

In [11]:
class BankAccount:
    # 이곳에 작성
    def __init__(self, account_number, balance=0):
        self.account_number = account_number
        self.balance = balance
    
    def deposit(self, amount):
        self.balance += amount

    def withdraw(self, amount):
        if self.balance >= amount:
            self.balance -= amount
            return
        print("잔액이 부족합니다")



account1 = BankAccount(12345, 1000)
account1.deposit(500)
account1.withdraw(200)
account1.withdraw(2000)  # 출력: 잔액이 부족합니다

잔액이 부족합니다

### 9. 다음과 같은 리스트가 주어졌을 때, max()와 min() 내장 함수를 사용하여 최댓값과 최솟값을 찾고 출력하는 코드를 작성하세요

In [12]:
numbers = [3, 7, 2, 1, 6, 4, 9, 8]

# 이곳에 작성
max_number = sorted(numbers,reverse=True)[0]
min_number = sorted(numbers)[0]
print("최댓값:", max_number)
print("최솟값:", min_number)

최댓값: 9
최솟값: 1

### 10. 아래 코드는 사용자로부터 숫자를 입력받아 제곱을 출력하는 코드입니다. 사용자가 숫자가 아닌 문자를 입력할 경우, ValueError 예외가 발생할 수 있습니다. 이 예외를 처리하고, 사용자에게 숫자를 입력하도록 안내하는 코드를 작성하세요.

In [15]:
# 이곳에 작성
while True:
   print('숫자를 입력하세요: ', end='')
   num = input()
   print(num)
   try:
      num = int(num)
   except ValueError:
      print("숫자를 입력해주세요.")
      continue
   print("입력한 숫자의 제곱:",num * num)
   break

숫자를 입력하세요: 10
입력한 숫자의 제곱: 100